[package]
name = "myspoonistoobig"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = "0.21.5"
humantime = "2.1.0"
crossbeam-channel = "0.5"